export interface LevelData {
  id: number;
  world: number;
  worldName: string;
  name: string;
  description: string;
  prefilled: { r: number; c: number; color: string }[];
}

export const WORLDS = [
  { id: 1, name: "Bioluminescent Deep", description: "Deep neon bioluminescent waters" },
  { id: 2, name: "Neon Abyss", description: "Vibrant high-contrast laser trenches" },
  { id: 3, name: "Astral Cosmos", description: "Starlit cosmic space and solar orbits" },
];

export const LEVELS_DATA: LevelData[] = [
  // WORLD 1: Bioluminescent Deep (Levels 1-5)
  {
    id: 1,
    world: 1,
    worldName: "Bioluminescent Deep",
    name: "Spark Beginning",
    description: "Clear the central square of bioluminescent pink blocks.",
    prefilled: [
      { r: 3, c: 3, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 3, c: 4, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 4, c: 3, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 4, c: 4, color: "from-neon-pink-from to-neon-pink-to" },
    ],
  },
  {
    id: 2,
    world: 1,
    worldName: "Bioluminescent Deep",
    name: "Tidal Slices",
    description: "Two parallel horizontal lines floating in the neon deep.",
    prefilled: [
      { r: 2, c: 2, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 2, c: 3, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 2, c: 4, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 2, c: 5, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 5, c: 2, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 5, c: 3, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 5, c: 4, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 5, c: 5, color: "from-neon-cyan-from to-neon-cyan-to" },
    ],
  },
  {
    id: 3,
    world: 1,
    worldName: "Bioluminescent Deep",
    name: "Coral Pillars",
    description: "Clear the two tall symmetrical vertical pillars of light.",
    prefilled: [
      { r: 1, c: 2, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 2, c: 2, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 3, c: 2, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 4, c: 2, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 5, c: 2, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 1, c: 5, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 2, c: 5, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 3, c: 5, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 4, c: 5, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 5, c: 5, color: "from-neon-purple-from to-neon-purple-to" },
    ],
  },
  {
    id: 4,
    world: 1,
    worldName: "Bioluminescent Deep",
    name: "Cyan Cross",
    description: "Symmetrical glowing cross sitting in the center.",
    prefilled: [
      { r: 3, c: 1, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 3, c: 2, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 3, c: 5, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 3, c: 6, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 1, c: 3, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 2, c: 3, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 5, c: 3, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 6, c: 3, color: "from-neon-cyan-from to-neon-cyan-to" },
    ],
  },
  {
    id: 5,
    world: 1,
    worldName: "Bioluminescent Deep",
    name: "The Deep Gate",
    description: "Unlock World 2 by completely clearing the massive neon gate block layout.",
    prefilled: [
      { r: 2, c: 2, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 2, c: 3, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 2, c: 4, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 2, c: 5, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 3, c: 2, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 3, c: 5, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 4, c: 2, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 4, c: 5, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 5, c: 2, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 5, c: 3, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 5, c: 4, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 5, c: 5, color: "from-neon-pink-from to-neon-pink-to" },
    ],
  },

  // WORLD 2: Neon Abyss (Levels 6-10)
  {
    id: 6,
    world: 2,
    worldName: "Neon Abyss",
    name: "Abyssal Ring",
    description: "Clearing a hollow outer ring requires smart row and column completions.",
    prefilled: [
      { r: 1, c: 1, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 1, c: 2, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 1, c: 5, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 1, c: 6, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 2, c: 1, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 2, c: 6, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 5, c: 1, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 5, c: 6, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 6, c: 1, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 6, c: 2, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 6, c: 5, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 6, c: 6, color: "from-neon-orange-from to-neon-orange-to" },
    ],
  },
  {
    id: 7,
    world: 2,
    worldName: "Neon Abyss",
    name: "Staggered Glitch",
    description: "Checkered prefilled layout of bioluminescent nodes.",
    prefilled: [
      { r: 0, c: 0, color: "from-neon-green-from to-neon-green-to" },
      { r: 0, c: 4, color: "from-neon-green-from to-neon-green-to" },
      { r: 2, c: 2, color: "from-neon-green-from to-neon-green-to" },
      { r: 2, c: 6, color: "from-neon-green-from to-neon-green-to" },
      { r: 4, c: 0, color: "from-neon-green-from to-neon-green-to" },
      { r: 4, c: 4, color: "from-neon-green-from to-neon-green-to" },
      { r: 6, c: 2, color: "from-neon-green-from to-neon-green-to" },
      { r: 6, c: 6, color: "from-neon-green-from to-neon-green-to" },
    ],
  },
  {
    id: 8,
    world: 2,
    worldName: "Neon Abyss",
    name: "Laser Horizon",
    description: "High and low border blocks spanning across the horizon.",
    prefilled: [
      { r: 0, c: 1, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 0, c: 3, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 0, c: 5, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 7, c: 2, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 7, c: 4, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 7, c: 6, color: "from-neon-pink-from to-neon-pink-to" },
    ],
  },
  {
    id: 9,
    world: 2,
    worldName: "Neon Abyss",
    name: "Submarine Anchor",
    description: "Heavier pre-filled layout mimicking a deep sea submarine anchor.",
    prefilled: [
      { r: 1, c: 3, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 1, c: 4, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 2, c: 3, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 2, c: 4, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 3, c: 1, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 3, c: 6, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 4, c: 1, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 4, c: 2, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 4, c: 5, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 4, c: 6, color: "from-neon-cyan-from to-neon-cyan-to" },
    ],
  },
  {
    id: 10,
    world: 2,
    worldName: "Neon Abyss",
    name: "Trench Squeeze",
    description: "Massive block pillars flanking both side walls. Clear them completely to unlock World 3!",
    prefilled: [
      { r: 2, c: 0, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 3, c: 0, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 4, c: 0, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 2, c: 7, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 3, c: 7, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 4, c: 7, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 3, c: 3, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 3, c: 4, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 4, c: 3, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 4, c: 4, color: "from-neon-pink-from to-neon-pink-to" },
    ],
  },

  // WORLD 3: Astral Cosmos (Levels 11-15)
  {
    id: 11,
    world: 3,
    worldName: "Astral Cosmos",
    name: "Meteor Spark",
    description: "Sparkles of prefilled blocks floating in diagonal alignments.",
    prefilled: [
      { r: 1, c: 1, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 2, c: 2, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 3, c: 3, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 4, c: 4, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 5, c: 5, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 6, c: 6, color: "from-neon-cyan-from to-neon-cyan-to" },
    ],
  },
  {
    id: 12,
    world: 3,
    worldName: "Astral Cosmos",
    name: "Nebula Wings",
    description: "Symmetrical wing patterns positioned around the central coordinate.",
    prefilled: [
      { r: 1, c: 0, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 1, c: 1, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 2, c: 1, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 1, c: 6, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 1, c: 7, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 2, c: 6, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 5, c: 1, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 6, c: 1, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 6, c: 0, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 5, c: 6, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 6, c: 6, color: "from-neon-orange-from to-neon-orange-to" },
      { r: 6, c: 7, color: "from-neon-orange-from to-neon-orange-to" },
    ],
  },
  {
    id: 13,
    world: 3,
    worldName: "Astral Cosmos",
    name: "Stellar Crosshair",
    description: "Dual cross patterns blocking line completions.",
    prefilled: [
      { r: 0, c: 3, color: "from-neon-green-from to-neon-green-to" },
      { r: 0, c: 4, color: "from-neon-green-from to-neon-green-to" },
      { r: 3, c: 0, color: "from-neon-green-from to-neon-green-to" },
      { r: 4, c: 0, color: "from-neon-green-from to-neon-green-to" },
      { r: 7, c: 3, color: "from-neon-green-from to-neon-green-to" },
      { r: 7, c: 4, color: "from-neon-green-from to-neon-green-to" },
      { r: 3, c: 7, color: "from-neon-green-from to-neon-green-to" },
      { r: 4, c: 7, color: "from-neon-green-from to-neon-green-to" },
    ],
  },
  {
    id: 14,
    world: 3,
    worldName: "Astral Cosmos",
    name: "Symmetric Nova",
    description: "Star pattern forming a stunning bioluminescent nova layout.",
    prefilled: [
      { r: 0, c: 3, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 1, c: 3, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 2, c: 3, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 3, c: 0, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 3, c: 1, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 3, c: 2, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 3, c: 5, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 3, c: 6, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 3, c: 7, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 4, c: 3, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 5, c: 3, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 7, c: 3, color: "from-neon-pink-from to-neon-pink-to" },
    ],
  },
  {
    id: 15,
    world: 3,
    worldName: "Astral Cosmos",
    name: "Ultimate Singularity",
    description: "The ultimate progressive puzzle layout. Achieve a perfect empty board to win!",
    prefilled: [
      { r: 1, c: 1, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 1, c: 6, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 2, c: 2, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 2, c: 5, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 3, c: 3, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 3, c: 4, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 4, c: 3, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 4, c: 4, color: "from-neon-cyan-from to-neon-cyan-to" },
      { r: 5, c: 2, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 5, c: 5, color: "from-neon-pink-from to-neon-pink-to" },
      { r: 6, c: 1, color: "from-neon-purple-from to-neon-purple-to" },
      { r: 6, c: 6, color: "from-neon-purple-from to-neon-purple-to" },
    ],
  },
];
